# Generated by Django 4.2.4 on 2023-08-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable', models.CharField(max_length=200)),
                ('sow_type', models.CharField(max_length=20)),
                ('harvest_days', models.IntegerField()),
                ('plant_spacing', models.IntegerField()),
                ('seed_depth', models.IntegerField()),
                ('sow_window_start', models.DateTimeField()),
                ('sow_window_end', models.DateTimeField()),
                ('transplant_window_start', models.DateTimeField()),
                ('transplant_window_end', models.DateTimeField()),
                ('harvest_window_start', models.DateTimeField()),
                ('harvest_window_end', models.DateTimeField()),
                ('vegetable_picture_url', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
