# Generated by Django 4.2.4 on 2023-08-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden_db',
            name='harvest_window_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='garden_db',
            name='harvest_window_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='garden_db',
            name='sow_window_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='garden_db',
            name='sow_window_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='garden_db',
            name='transplant_window_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='garden_db',
            name='transplant_window_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='garden_db',
            name='vegetable_picture_url',
            field=models.CharField(max_length=500),
        ),
    ]
