# Generated by Django 4.2.4 on 2023-08-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_alter_garden_db_harvest_window_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden_db',
            name='seed_depth',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
