# Generated by Django 4.2.4 on 2023-08-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_alter_garden_db_harvest_window_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden_db',
            name='date_created',
        ),
    ]
