# Generated by Django 4.2.4 on 2023-08-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_remove_garden_db_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden_db',
            name='seed_depth',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
